# Generated by Django 6.0 on 2026-01-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名稱")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="價格"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dress", "洋裝"),
                            ("top", "上衣"),
                            ("bottom", "下身"),
                            ("two-piece", "套裝"),
                            ("outerwear", "外套"),
                        ],
                        max_length=50,
                        verbose_name="分類",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="products/original/", verbose_name="原始圖片"
                    ),
                ),
                (
                    "image_nobg",
                    models.ImageField(
                        blank=True, upload_to="products/nobg/", verbose_name="去背圖片"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="標籤")),
                (
                    "colors",
                    models.JSONField(blank=True, default=list, verbose_name="顏色"),
                ),
                (
                    "occasion",
                    models.JSONField(blank=True, default=list, verbose_name="場合"),
                ),
                (
                    "season",
                    models.JSONField(blank=True, default=list, verbose_name="季節"),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("elegant", "優雅"),
                            ("casual", "休閒"),
                            ("sexy", "性感"),
                            ("sweet", "甜美"),
                            ("cool", "酷帥"),
                        ],
                        max_length=50,
                        verbose_name="風格",
                    ),
                ),
                (
                    "material",
                    models.CharField(blank=True, max_length=100, verbose_name="材質"),
                ),
                (
                    "sleeve",
                    models.CharField(blank=True, max_length=50, verbose_name="袖長"),
                ),
                (
                    "length",
                    models.CharField(blank=True, max_length=100, verbose_name="長度"),
                ),
                (
                    "neckline",
                    models.CharField(blank=True, max_length=50, verbose_name="領型"),
                ),
                ("fit", models.CharField(blank=True, max_length=50, verbose_name="版型")),
                (
                    "color_temperature",
                    models.CharField(blank=True, max_length=50, verbose_name="色溫"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["id"],
            },
        ),
    ]
