# Generated by Django 6.0 on 2026-01-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(
                blank=True, help_text="例如：手洗、不可烘乾", verbose_name="洗滌說明"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.CharField(
                blank=True, help_text="例如：95%棉 5%氨綸", max_length=200, verbose_name="成分"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="商品特色與賣點", verbose_name="商品描述"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="上架中"),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="原價",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_info",
            field=models.TextField(
                blank=True, help_text="尺寸表或尺寸建議", verbose_name="尺寸資訊"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="商品編號"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="庫存數量"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("dress", "洋裝"),
                    ("top", "上衣"),
                    ("pants", "長褲"),
                    ("shorts", "短褲"),
                    ("skirt", "裙子"),
                    ("two-piece", "套裝"),
                    ("jacket", "外套"),
                ],
                max_length=50,
                verbose_name="分類",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="售價"
            ),
        ),
    ]
